### ISSUE TITLE
fix: rendering on next major iOS version

### ISSUE THREAD

**Issue by HBehrens** [BeamApp/MusicPlayerViewController#15]
in general: 
- offset of view (and subsequently navigation bar, scrubbing area, etc.)
- tinting of buttons

on iPad:
- background color of popover when presenting playlist

**Comment by DerPipo** [comment]
I don't have access to iOS 7, because i'm running Lion, so i don't have an idea what the Music.app looks like. Can you post some screenshots how it should look like on iOS 7?

**Comment by HBehrens** [comment]
This ticket does not ask for adopting of look of the upcoming iOS version as #12 does. Instead, the points mentioned above describe how the _current_ look is layouted falsy on iOS 7. That way, every existing app running the current version of this library will have some visual glitches after users have updated their iOS version.

As far as I can see, there are only minor adjustments needed to make it work on any version from 5.0 onwards.

**Comment by DerPipo** [comment]
Ah, i see.
